# Generated by Django 6.0.2 on 2026-02-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('provider', models.CharField(max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
