# Generated by Django 6.0.2 on 2026-02-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_watchlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='tmdb_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('tmdb_id', 'provider')},
        ),
    ]
